Divar/Controllers/AddController.cs
using Divar.Db;
using Divar.Interfaces;
using Divar.Mapper;
using Divar.Services;
using Divar.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Localization;
using System;
using System.Globalization;
using System.Text.Json;

namespace Divar.Controllers
{
    
    public class AddController : Controller
    {
        private readonly DivarContext _context;
        private readonly IStringLocalizer<AddController> _localizer;
        private readonly ILocalizationService _localizationService;
        private readonly IAdvertisementService _advertisementService;
        public List<Category> categories;
        private readonly ICityService _cityService;
        private readonly ICategoryService _categoryService;

        List<List<Category>> cats = new List<List<Category>>();
        Dictionary<string, List<Category>> catsDictionary = new Dictionary<string, List<Category>>();
        //public List<City> cities;

        //private readonly AdvertisementMapper _advertisementMapper;

        public AddController(DivarContext db, IStringLocalizer<AddController> localizer, ICityService cityService, ICategoryService categoryService, IAdvertisementService advertisementService, ILocalizationService localizationService)
        {
            _context = db;
            _localizer = localizer;
            _advertisementService = advertisementService;
            _localizationService = localizationService;
            _cityService = cityService;
            _categoryService = categoryService;
            //cities = _context.Cities.ToList();

            //_advertisementMapper = advertisementMapper;
        }
        //[HttpGet("ads/add")]
        //[HttpGet("advertisements/add")]
        //[HttpGet("items/add")]
        [HttpGet("add")]
        public async Task<IActionResult> Index()
        {

            //var tuple = new Tuple<Advertisement, DivarContext>(new Advertisement(),new DivarContext());
            //return View(tuple);
            //Tuple<Advertisement, List<Category>> tuple = new Tuple<Advertisement, List<Category>>(new Advertisement(), categories);


            //List<Category> categories = new List<Category>();
            //foreach (var item in _context.Categories.ToList<Category>())
            //{
            //    categories.Add(item);
            //}
            //ViewData["categories"] = categories;

            //List<Category> cs = new List<Category>();
            //foreach (var item in categories)
            //{
            //    cs.Add(item);
            //}

            //ViewData["categories"] = cs;

            categories= await _context.Categories.ToListAsync<Category>();
            List<Category> cs = new List<Category>();
            foreach (var item in categories)
            {
                cs.Add(item);
            }

            ViewData["categories"] = cs;

            //ViewData["BasePriceAddViewData"] = _localizer["BasePriceAdd"];
            //ViewData["BrandAddViewData"] = _localizer["BrandAdd"];
            //ViewData["CategoryIdAddViewData"] = _localizer["CategoryIdAdd"];
            //ViewData["ChassisAndBodyConditionAddViewData"] = _localizer["ChassisAndBodyConditionAdd"];
            //ViewData["CityIdAddViewData"] = _localizer["CityIdAdd"];
            //ViewData["ColorAddViewData"] = _localizer["ColorAdd"];
            //ViewData["DescriptionAddViewData"] = _localizer["DescriptionAdd"];
            //ViewData["DoYouWantToReplaceAddViewData"] = _localizer["DoYouWantToReplaceAdd"];
            //ViewData["EngineConditionAddViewData"] = _localizer["EngineConditionAdd"];
            //ViewData["FrontChassisConditionAddViewData"] = _localizer["FrontChassisConditionAdd"];
            //ViewData["FunctionKilometersAddViewData"] = _localizer["FunctionKilometersAdd"];
            //ViewData["GearboxAddViewData"] = _localizer["GearboxAdd"];
            //ViewData["IsTheChatActivatedAddViewData"] = _localizer["IsTheChatActivatedAdd"];
            //ViewData["IsThePhoneCallActiveAddViewData"] = _localizer["IsThePhoneCallActiveAdd"];
            //ViewData["ItsModelAddViewData"] = _localizer["ItsModelAdd"];
            //ViewData["NationalCodeAddViewData"] = _localizer["NationalCodeAdd"];
            //ViewData["NationalityAddViewData"] = _localizer["NationalityAdd"];
            //ViewData["RearChassisConditionAddViewData"] = _localizer["RearChassisConditionAdd"];
            //ViewData["ThirdPartyInsuranceTermAddViewData"] = _localizer["ThirdPartyInsuranceTermAdd"];
            //ViewData["TitleAddViewData"] = _localizer["TitleAdd"];
            //ViewData["SubmitAddViewData"] = _localizer["SubmitAdd"];
            //ViewData["RequiredInputErrorAddViewData"] = _localizer["RequiredInputError"];
            //ViewData["HomeMenueLayouteViewData"] = _localizer["HomeMenueLayoute"];
            //ViewData["AddAdMenueLayouteViewData"] = _localizer["AddAdMenueLayoute"];

            //switch (CultureInfo.CurrentCulture.ToString())
            //{
            //    case "en-US":
            //        ViewData["dir"] = "ltr";
            //        break;
            //    case "fa-IR":
            //        ViewData["dir"] = "rtl";
            //        break;
            //}
            //if (CultureInfo.CurrentCulture.ToString() == "fa-IR")
            //{
            //    ViewData["dir"] = "rtl";
            //}
            //else
            //{
            //    ViewData["dir"] = "ltr";
            //}

            return View("Index");
        }


        //[HttpPost("ads/add")]
        //[HttpPost("advertisements/add")]
        //[HttpPost("items/add")]
        [HttpPost("add")]
        [ValidateAntiForgeryToken]
public async Task<IActionResult> Index(AddViewModel model)
        {
            categories = await _context.Categories.ToListAsync<Category>();
            List<Category> cs = new List<Category>();
            foreach (var item in categories)
            {
                cs.Add(item);
            }

            ViewData["categories"] = cs;

            //ViewData["BasePriceAddViewData"] = _localizer["BasePriceAdd"];
            //ViewData["BrandAddViewData"] = _localizer["BrandAdd"];
            //ViewData["CategoryIdAddViewData"] = _localizer["CategoryIdAdd"];
            //ViewData["ChassisAndBodyConditionAddViewData"] = _localizer["ChassisAndBodyConditionAdd"];
            //ViewData["CityIdAddViewData"] = _localizer["CityIdAdd"];
            //ViewData["ColorAddViewData"] = _localizer["ColorAdd"];
            //ViewData["DescriptionAddViewData"] = _localizer["DescriptionAdd"];
            //ViewData["DoYouWantToReplaceAddViewData"] = _localizer["DoYouWantToReplaceAdd"];
            //ViewData["EngineConditionAddViewData"] = _localizer["EngineConditionAdd"];
            //ViewData["FrontChassisConditionAddViewData"] = _localizer["FrontChassisConditionAdd"];
            //ViewData["FunctionKilometersAddViewData"] = _localizer["FunctionKilometersAdd"];
            //ViewData["GearboxAddViewData"] = _localizer["GearboxAdd"];
            //ViewData["IsTheChatActivatedAddViewData"] = _localizer["IsTheChatActivatedAdd"];
            //ViewData["IsThePhoneCallActiveAddViewData"] = _localizer["IsThePhoneCallActiveAdd"];
            //ViewData["ItsModelAddViewData"] = _localizer["ItsModelAdd"];
            //ViewData["NationalCodeAddViewData"] = _localizer["NationalCodeAdd"];
            //ViewData["NationalityAddViewData"] = _localizer["NationalityAdd"];
            //ViewData["RearChassisConditionAddViewData"] = _localizer["RearChassisConditionAdd"];
            //ViewData["ThirdPartyInsuranceTermAddViewData"] = _localizer["ThirdPartyInsuranceTermAdd"];
            //ViewData["TitleAddViewData"] = _localizer["TitleAdd"];
            //ViewData["SubmitAddViewData"] = _localizer["SubmitAdd"];
            //ViewData["RequiredInputErrorAddViewData"] = _localizer["RequiredInputErrorAdd"];
            string sellll = HttpContext.Request.Cookies["sellerId"];
            if (sellll != null)
            {
                int sel = JsonSerializer.Deserialize<int>(sellll);
                var seller = _context.Sellers.Where(x => x.Id == sel).FirstOrDefault();
                if (seller != null)
                {
                    ViewData["sellerfirstname"] = seller.FirstName + " عزیز خوش آمدی ";


                }


            }
            else
            {

                ViewData["sellerfirstname"] = "ثبت نام نکرده اید";
            }




            var Viesws = await _advertisementService.GetAllAdvertisementsAsyncHomeVM();
            foreach (var ad in Viesws)
            {
                var breadcrumbs = await _categoryService.GetBreadcrumbsAsync((int)ad.CategoryId);

                ViewData["breadcrumbs" + ad.Id.ToString()] = breadcrumbs;
                catsDictionary["breadcrumbs" + ad.Id.ToString()] = breadcrumbs;
                this.cats.Add(breadcrumbs);

                var city = await _cityService.GetCityByIdAsync((int)ad.CityId);
                ViewData["city" + ad.Id.ToString()] = city.Name;
            }


            if (!ModelState.IsValid)
            {
                //Tuple<Advertisement, List<Category>> tuplee = new Tuple<Advertisement, List<Category>>(new Advertisement(), categories);
                return View("../Home/Index",Viesws);
            };
            //Tuple<Advertisement, List<Category>> tuple = new Tuple<Advertisement, List<Category>>(new Advertisement(), categories);



            await _advertisementService.AddAdvertisementAsync(model);

            return View("../Home/Index", Viesws);
        }


        public async Task<IActionResult> ChangeCulture(string culture)
        {

            //categories = await _context.Categories.ToListAsync<Category>();
            //List<Category> cs = new List<Category>();
            //foreach (var item in categories)
            //{
            //    cs.Add(item);

Divar/Controllers/SellerController.cs
using Divar.Db;
using Divar.Interfaces;
using Divar.Services;
using Divar.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.IdentityModel.Tokens;
using System.Globalization;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Divar.Controllers
{
    public class SellerController : Controller
    {
        private readonly ILogger<SellerController> _logger;
        private readonly DivarContext _context;
        //private readonly IStringLocalizer<HomeController> _localizer;
        //private readonly ILocalizationService _localizationService;

        private readonly ISellercService _sellercsService;
        public SellerController(ILogger<SellerController> logger, DivarContext db, IStringLocalizer<HomeController> localizer, ISellercService sellercsService)
        {
            _context = db;
            _logger = logger;
            //_localizer = localizer;
            _sellercsService = sellercsService;
            //_localizationService = localizationService;
            //categories = _context.Categories.ToList<Category>();

            //_advertisementMapper = advertisementMapper;
        }

        public async Task<IActionResult> Index()
        {
            var Viesws = await _sellercsService.GetAllSellersAsyncSellerVM();

            return View("Index", Viesws);


        }
        [HttpPost]
        public async Task<IActionResult> Index(string SearchString)
        {
            var memberList = await _sellercsService.GetAllSellersAsyncSellerVM();
            if (!ModelState.IsValid)
            {
                return View("Index", memberList);
            }
            if (!SearchString.IsNullOrEmpty())
            {
                var ads = await _sellercsService.SearchSellersAsync(SearchString);
                return View("Index", ads);
            }
            return View("Index", memberList);
        }
        public async Task<IActionResult> SignUp()
        {
            return View("../Seller/SignUp");
        }
        public async Task<IActionResult> LogIn()
        {
            return View("../Seller/LogIn");
        }


        //[HttpPost("ads/add")]
        //[HttpPost("advertisements/add")]
        //[HttpPost("items/add")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp(SellerSignUpViewModel model)
        {
            var Viesws = await _sellercsService.GetAllSellersAsyncSellerVM();
            if (!ModelState.IsValid)
            {
                //Tuple<Advertisement, List<Category>> tuplee = new Tuple<Advertisement, List<Category>>(new Advertisement(), categories);
                return View("../Seller/Index", Viesws);
            }
            ;
            //Tuple<Advertisement, List<Category>> tuple = new Tuple<Advertisement, List<Category>>(new Advertisement(), categories);



            await _sellercsService.AddSellerAsync(model);

            return View("../Seller/Index", Viesws);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogIn(SellerLogInViewModel model)
        {
                var Viesws = await _sellercsService.GetAllSellersAsyncSellerVM();
                if (!ModelState.IsValid)
            {
                //Tuple<Advertisement, List<Category>> tuplee = new Tuple<Advertisement, List<Category>>(new Advertisement(), categories);
                return View("../Seller/Index", Viesws);
            }
            ;
            //Tuple<Advertisement, List<Category>> tuple = new Tuple<Advertisement, List<Category>>(new Advertisement(), categories);



            await _sellercsService.LogInSellerAsync(model.NationalCode);

            return View("../Seller/Index", Viesws);
        }
        public async Task<IActionResult> Details(int id)
        {

            var seller = await _sellercsService.GetSellerByIdAsyncSellerDetailsVM(id);
            if (seller == null)
            {
                return NotFound("محصولی با این شناسه یافت نشد.");
            }

            return View(seller);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _sellercsService.DeleteSellerAsync(id);
            var Viesws = await _sellercsService.GetAllSellersAsyncSellerVM();
            return View("../Seller/Index", Viesws);
        }

        public async Task<IActionResult> Edit(int id)
        {

            var view = await _sellercsService.GetSellerByIdAsyncSellerEditVM(id);
            if (view == null) return NotFound();
            return View(view);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SellerEditViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View("Details");
            };

            await _sellercsService.UpdateSellerAsync(model);
            var view = await _sellercsService.GetSellerByIdAsyncSellerDetailsVM(model.Id);


            return View("Details", view);

        }
    }
}

Divar/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Localization
@using Divar.Services
@using Divar.Interfaces
@using System.Globalization
@inject IStringLocalizer<Divar.Controllers.HomeController>   _localizer;
@inject ILocalizationService LocalizationService;
<!DOCTYPE html>
@* <html lang="en" dir="@ViewData["dir"]"> *@
<html lang="en" dir="@LocalizationService.GetLocalizedDir()">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practise1Divar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.@(LocalizationService.GetLocalizedDir()).min.css" />
    @*<link rel="stylesheet" href="@LocalizationService.GetlocalizedBootstrapLink()" />*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practise1Divar.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <!--<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practise1Divar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>-->

    <!--<a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>-->

          


<nav class="navbar navbar-expand bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">

        <li class="nav-item">
   <a asp-action="Index" asp-controller="Home" class="nav-link" aria-current="page">@_localizer["HomeMenueLayoute"]</a>
                            @* <a asp-action="Index" asp-controller="Home" class="nav-link" aria-current="page">@ViewData["HomeMenueLayouteViewData"]</a> *@
</li>
                        <li class="nav-item">

                            @* <a asp-action="Index" asp-controller="Add" class="nav-link" aria-current="page">@ViewData["AddAdMenueLayouteViewData"]</a> *@
                            <a asp-action="Index" asp-controller="Add" class="nav-link" aria-current="page">@_localizer["AddAdMenueLayoute"]</a>
                        </li>
                        <li class="nav-item">

                            @* <a asp-action="Index" asp-controller="Add" class="nav-link" aria-current="page">@ViewData["AddAdMenueLayouteViewData"]</a> *@
                            <a asp-action="Index" asp-controller="Seller" class="nav-link" aria-current="page">Sellers</a>
                        </li>
                        <li class="nav-item">

                            @* <a asp-action="Index" asp-controller="Add" class="nav-link" aria-current="page">@ViewData["AddAdMenueLayouteViewData"]</a> *@
                            <a asp-action="SignUp" asp-controller="Seller" class="nav-link" aria-current="page">Sign up</a>
                        </li>
      </ul>
    </div>
  </div>
</nav>
        @*@{
            var newCulture = CultureInfo.CurrentCulture.Name == "en-US" ? "fa-IR" : "en-US";
            var newAction = this.ViewContext.RouteData.Values["action"].ToString();
        }
        <a class="btn btn-primary" asp-action="ChangeCulture" asp-controller="@(ViewContext.RouteData.Values["controller"])" asp-route-culture="@newCulture" asp-route-action="@newAction">
            <i class="bi bi-translate"></i>
        </a>*@
        @{
            var currentCulture = CultureInfo.CurrentCulture.Name;
            var newCulture = currentCulture == "fa-IR" ? "en-US" : "fa-IR";
            // var path = Context.Request.Path;
        }
        @*<div>
            <a class="btn btn-primary" onclick="@LocalizationService.ChangeCultureInfo(newCulture)" asp-route-culture="@newCulture">
                <i class="bi bi-translate"></i>
            </a>
        </div>*@
        <a class="btn btn-primary" asp-action="ChangeCulture" asp-controller="Home" asp-route-culture="@newCulture">
            <i class="bi bi-translate"></i>
        </a>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <!--<div class="container">
            &copy; 2024 - Practise1Divar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>-->
        </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>